version: "3.8"
services:
    web:
        build: ./my_site
        command: python3 /lab3/manage.py runserver 0.0.0.0:8000
        ports: 
            - '8000:8000'
        depends_on: 
            - db
    db:
        image: postgres:12.0-alpine
        ports:
            - '5432'
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
volumes: 
    postgres_data: